added new version of Elasticsearch 5.3.0. Updated installation script.

diff --git a/Toolkits/Elasticsearch/bin/elasticsearch b/Toolkits/Elasticsearch/bin/elasticsearch
--- a/Toolkits/Elasticsearch/bin/elasticsearch
+++ b/Toolkits/Elasticsearch/bin/elasticsearch
@@ -1,15 +1,4 @@
-#!/bin/sh
-
-# OPTIONS:
-#    -d            daemonize (run in background)
-#    -p pidfile    write PID to <pidfile>
-#    -h
-#    --help        print command line options
-#    -v            print elasticsearch version, then exit
-#    -D prop       set JAVA system property
-#    -X prop       set non-standard JAVA system property
-#   --prop=val
-#   --prop val     set elasticsearch property (i.e.  -Des.<prop>=<val>)
+#!/bin/bash
 
 # CONTROLLING STARTUP:
 #
@@ -17,14 +6,14 @@
 # behavior, those variables are:
 #
 #   ES_CLASSPATH -- A Java classpath containing everything necessary to run.
-#   JAVA_OPTS    -- Additional arguments to the JVM for heap size, etc
+#   ES_JVM_OPTIONS -- Path to file containing JVM options
 #   ES_JAVA_OPTS -- External Java Opts on top of the defaults set
 #
+# Optionally, exact memory values can be set using the `ES_JAVA_OPTS`.
+# Note that the Xms and Xmx lines in the JVM options file must be
+# commented out. Sample format include "512m", and "10g".
 #
-# Optionally, exact memory values can be set using the following values, note,
-# they can still be set using the `ES_JAVA_OPTS`. Sample format include "512m", and "10g".
-#
-#   ES_HEAP_SIZE -- Sets both the minimum and maximum memory to allocate (recommended)
+#   ES_JAVA_OPTS="-Xms8g -Xmx8g" ./bin/elasticsearch
 #
 # As a convenience, a fragment of shell is sourced in order to set one or
 # more of these variables. This so-called `include' can be placed in a
@@ -53,19 +42,52 @@
 # Be aware that you will be entirely responsible for populating the needed
 # environment variables.
 
+# Check to see if you are trying to run this without building it first. Gradle
+# will replace the project.name with _something_.
 
-# Maven will replace the project.name with elasticsearch below. If that
-# hasn't been done, we assume that this is not a packaged version and the
-# user has forgotten to run Maven to create a package.
-IS_PACKAGED_VERSION='elasticsearch'
-if [ "$IS_PACKAGED_VERSION" != "elasticsearch" ]; then
+if echo 'distribution' | grep project.name > /dev/null ; then
     cat >&2 << EOF
-Error: You must build the project with Maven or download a pre-built package
+Error: You must build the project with Gradle or download a pre-built package
 before you can run Elasticsearch. See 'Building from Source' in README.textile
-or visit http://www.elasticsearch.org/download to get a pre-built package.
+or visit https://www.elastic.co/download to get a pre-built package.
 EOF
     exit 1
 fi
+
+# TODO: remove for Elasticsearch 6.x
+unsupported_environment_variable() {
+    if test -n "$1"; then
+        echo "$2=$1: $3"
+    fi
+}
+
+if test -n "$ES_MIN_MEM" ||
+   test -n "$ES_MAX_MEM" ||
+   test -n "$ES_HEAP_SIZE" ||
+   test -n "$ES_HEAP_NEWSIZE" ||
+   test -n "$ES_DIRECT_SIZE" ||
+   test -n "$ES_USE_IPV4" ||
+   test -n "$ES_GC_OPTS" ||
+   test -n "$ES_GC_LOG_FILE"; then
+    echo "Error: encountered environment variables that are no longer supported"
+    echo "Use jvm.options or ES_JAVA_OPTS to configure the JVM"
+    unsupported_environment_variable "$ES_MIN_MEM" ES_MIN_MEM "set -Xms$ES_MIN_MEM in jvm.options or add \"-Xms$ES_MIN_MEM\" to ES_JAVA_OPTS"
+    unsupported_environment_variable "$ES_MAX_MEM" ES_MAX_MEM "set -Xmx$ES_MAX_MEM in jvm.options or add \"-Xmx$ES_MAX_MEM\" to ES_JAVA_OPTS"
+    unsupported_environment_variable "$ES_HEAP_SIZE" ES_HEAP_SIZE "set -Xms$ES_HEAP_SIZE and -Xmx$ES_HEAP_SIZE in jvm.options or add \"-Xms$ES_HEAP_SIZE -Xmx$ES_HEAP_SIZE\" to ES_JAVA_OPTS"
+    unsupported_environment_variable "$ES_HEAP_NEWSIZE" ES_HEAP_NEWSIZE "set -Xmn$ES_HEAP_NEWSIZE in jvm.options or add \"-Xmn$ES_HEAP_SIZE\" to ES_JAVA_OPTS"
+    unsupported_environment_variable "$ES_DIRECT_SIZE" ES_DIRECT_SIZE "set -XX:MaxDirectMemorySize=$ES_DIRECT_SIZE in jvm.options or add \"-XX:MaxDirectMemorySize=$ES_DIRECT_SIZE\" to ES_JAVA_OPTS"
+    unsupported_environment_variable "$ES_USE_IPV4" ES_USE_IPV4 "set -Djava.net.preferIPv4Stack=true in jvm.options or add \"-Djava.net.preferIPv4Stack=true\" to ES_JAVA_OPTS"
+    unsupported_environment_variable "$ES_GC_OPTS" ES_GC_OPTS "set ${ES_GC_OPTS// / and } in jvm.options or add \"$ES_GC_OPTS\" to ES_JAVA_OPTS"
+    unsupported_environment_variable "$ES_GC_LOG_FILE" ES_GC_LOG_FILE "set -Xloggc:$ES_GC_LOG_FILE in jvm.options or add \"-Xloggc:$ES_GC_LOG_FILE\" to ES_JAVA_OPTS"
+    exit 1
+fi
+# end TODO: remove for Elasticsearch 6.x
+
+parse_jvm_options() {
+  if [ -f "$1" ]; then
+    echo "$(grep "^-" "$1" | tr '\n' ' ')"
+  fi
+}
 
 CDPATH=""
 SCRIPT="$0"
@@ -88,6 +110,17 @@ ES_HOME=`dirname "$SCRIPT"`/..
 # make ELASTICSEARCH_HOME absolute
 ES_HOME=`cd "$ES_HOME"; pwd`
 
+if [ -z "$ES_JVM_OPTIONS" ]; then
+    for jvm_options in "$ES_HOME"/config/jvm.options \
+                      /etc/elasticsearch/jvm.options; do
+        if [ -r "$jvm_options" ]; then
+            ES_JVM_OPTIONS=$jvm_options
+            break
+        fi
+    done
+fi
+
+ES_JAVA_OPTS="$(parse_jvm_options "$ES_JVM_OPTIONS") $ES_JAVA_OPTS"
 
 # If an include wasn't specified in the environment, then search for one...
 if [ "x$ES_INCLUDE" = "x" ]; then
@@ -96,7 +129,7 @@ if [ "x$ES_INCLUDE" = "x" ]; then
                    /usr/local/share/elasticsearch/elasticsearch.in.sh \
                    /opt/elasticsearch/elasticsearch.in.sh \
                    ~/.elasticsearch.in.sh \
-                   $ES_HOME/bin/elasticsearch.in.sh \
+                   "$ES_HOME/bin/elasticsearch.in.sh" \
                    "`dirname "$0"`"/elasticsearch.in.sh; do
         if [ -r "$include" ]; then
             . "$include"
@@ -124,128 +157,51 @@ if [ -z "$ES_CLASSPATH" ]; then
     exit 1
 fi
 
-# Special-case path variables.
-case `uname` in
-    CYGWIN*)
-        ES_CLASSPATH=`cygpath -p -w "$ES_CLASSPATH"`
-        ES_HOME=`cygpath -p -w "$ES_HOME"`
-    ;;
-esac
+# don't let JAVA_TOOL_OPTIONS slip in (e.g. crazy agents in ubuntu)
+# works around https://bugs.launchpad.net/ubuntu/+source/jayatana/+bug/1441487
+if [ "x$JAVA_TOOL_OPTIONS" != "x" ]; then
+    echo "Warning: Ignoring JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
+    echo "Please pass JVM parameters via ES_JAVA_OPTS instead"
+    unset JAVA_TOOL_OPTIONS
+fi
 
-launch_service()
-{
-    pidpath=$1
-    daemonized=$2
-    props=$3
-    es_parms="-Delasticsearch"
+# JAVA_OPTS is not a built-in JVM mechanism but some people think it is
+# so let us warn them that we are not observing the value of $JAVA_OPTS
+if [ "x$JAVA_OPTS" != "x" ]; then
+    echo "Warning: Ignoring JAVA_OPTS=$JAVA_OPTS"
+    echo "Please pass JVM parameters via ES_JAVA_OPTS instead"
+fi
 
-    if [ "x$pidpath" != "x" ]; then
-        es_parms="$es_parms -Des.pidfile=$pidpath"
+"$JAVA" -cp "$ES_CLASSPATH" org.elasticsearch.tools.JavaVersionChecker
+
+if [ $? -ne 0 ]; then
+    echo "Elasticsearch requires at least Java 8 but your Java version from $JAVA does not meet this requirement"
+    exit 1
+fi
+
+# full hostname passed through cut for portability on systems that do not support hostname -s
+# export on separate line for shells that do not support combining definition and export
+HOSTNAME=`hostname | cut -d. -f1`
+export HOSTNAME
+
+# manual parsing to find out, if process should be detached
+daemonized=`echo $* | egrep -- '(^-d |-d$| -d |--daemonize$|--daemonize )'`
+if [ -z "$daemonized" ] ; then
+    exec "$JAVA" $ES_JAVA_OPTS -Des.path.home="$ES_HOME" -cp "$ES_CLASSPATH" \
+          org.elasticsearch.bootstrap.Elasticsearch "$@"
+else
+    exec "$JAVA" $ES_JAVA_OPTS -Des.path.home="$ES_HOME" -cp "$ES_CLASSPATH" \
+          org.elasticsearch.bootstrap.Elasticsearch "$@" <&- &
+    retval=$?
+    pid=$!
+    [ $retval -eq 0 ] || exit $retval
+    if [ ! -z "$ES_STARTUP_SLEEP_TIME" ]; then
+      sleep $ES_STARTUP_SLEEP_TIME
     fi
-
-    # Make sure we dont use any predefined locale, as we check some exception message strings and rely on english language
-    # As those strings are created by the OS, they are dependant on the configured locale
-    LANG=en_US.UTF-8
-    LC_ALL=en_US.UTF-8
-
-    export HOSTNAME=`hostname -s`
-
-    # The es-foreground option will tell Elasticsearch not to close stdout/stderr, but it's up to us not to daemonize.
-    if [ "x$daemonized" = "x" ]; then
-        es_parms="$es_parms -Des.foreground=yes"
-        exec "$JAVA" $JAVA_OPTS $ES_JAVA_OPTS $es_parms -Des.path.home="$ES_HOME" -cp "$ES_CLASSPATH" $props \
-                org.elasticsearch.bootstrap.Elasticsearch
-        # exec without running it in the background, makes it replace this shell, we'll never get here...
-        # no need to return something
-    else
-        # Startup Elasticsearch, background it, and write the pid.
-        exec "$JAVA" $JAVA_OPTS $ES_JAVA_OPTS $es_parms -Des.path.home="$ES_HOME" -cp "$ES_CLASSPATH" $props \
-                    org.elasticsearch.bootstrap.Elasticsearch <&- &
-        return $?
+    if ! ps -p $pid > /dev/null ; then
+      exit 1
     fi
-}
-
-# Print command line usage / help
-usage() {
-    echo "Usage: $0 [-vdh] [-p pidfile] [-D prop] [-X prop]"
-    echo "Start elasticsearch."
-    echo "    -d            daemonize (run in background)"
-    echo "    -p pidfile    write PID to <pidfile>"
-    echo "    -h"
-    echo "    --help        print command line options"
-    echo "    -v            print elasticsearch version, then exit"
-    echo "    -D prop       set JAVA system property"
-    echo "    -X prop       set non-standard JAVA system property"
-    echo "   --prop=val"
-    echo "   --prop val     set elasticsearch property (i.e. -Des.<prop>=<val>)"
-}
-
-# Parse any long getopt options and put them into properties before calling getopt below
-# Be dash compatible to make sure running under ubuntu works
-ARGV=""
-while [ $# -gt 0 ]
-do
-    case $1 in
-      --help) ARGV="$ARGV -h"; shift;;
-      --*=*) properties="$properties -Des.${1#--}"
-           shift 1
-           ;;
-      --*) [ $# -le 1 ] && {
-                echo "Option requires an argument: '$1'."
-                shift
-                continue
-            }
-           properties="$properties -Des.${1#--}=$2"
-           shift 2
-           ;;
-      *) ARGV="$ARGV $1" ; shift
-    esac
-done
-
-# Parse any command line options.
-args=`getopt vdhp:D:X: $ARGV`
-eval set -- "$args"
-
-while true; do
-    case $1 in
-        -v)
-            "$JAVA" $JAVA_OPTS $ES_JAVA_OPTS $es_parms -Des.path.home="$ES_HOME" -cp "$ES_CLASSPATH" $props \
-                    org.elasticsearch.Version
-            exit 0
-        ;;
-        -p)
-            pidfile="$2"
-            shift 2
-        ;;
-        -d)
-            daemonized="yes"
-            shift
-        ;;
-        -h)
-            usage
-            exit 0
-        ;;
-        -D)
-            properties="$properties -D$2"
-            shift 2
-        ;;
-        -X)
-            properties="$properties -X$2"
-            shift 2
-        ;;
-        --)
-            shift
-            break
-        ;;
-        *)
-            echo "Error parsing argument $1!" >&2
-            usage
-            exit 1
-        ;;
-    esac
-done
-
-# Start up the service
-launch_service "$pidfile" "$daemonized" "$properties"
+    exit 0
+fi
 
 exit $?
